[build]
  publish = "."
  command = "# Pas de commande de build nÃ©cessaire pour un site statique"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
